// TODO: Create a function to generate markdown for README
function generateReadme(answers) {
  return `
<h1 align="center">${answers.title}</h1>

## Description
🔍 ${answers.description}

## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)

## Installation
💾 ${answers.installation}

## Usage
💻 ${answers.usage}

## License
<br />
This application is covered by the ${answers.license} license. 

## Contributing
👪 ${answers.contributing}

## Tests
✏️ ${answers.tests}

## Questions
✋ ${answers.questions}<br />
<br />
This readme was generated by ${answers.name} <br />
:octocat: GitHub: [${answers.github}](https://github.com/${answers.github})<br />
<br />
  `;
}

module.exports = generateReadme;